<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Car extends Model
{
    use HasFactory;
    protected $guarded = [];
    public $timestamps = false;
    public static string $imagePath = "public/images";

    protected $casts = [
        'return_date' => 'date',
        'pickup_date' => 'date',
        'reserved_at' => 'datetime',
        'picked_up_at' => 'timestamp',
        'returned_at' => 'timestamp',
    ];

    public function image() : Attribute
    {
        return Attribute::get(
            function($image) {
                if(!$image || !Storage::exists(self::$imagePath . "/$image")) {
                    return asset("images/car.png");
                }

                return Storage::get(self::$imagePath . "/$image");
            },
        );
    }
    public function paginate($perPage = 10, $columns = ['*'], $pageName = 'page', $page = null)
    {


        return parent::paginate($perPage, $columns, $pageName, $page);

    }
    public function find($id, $columns = ['*'])
    {
        return parent::find($id, $columns); // TODO: Change the autogenerated stub
    }
}
